export default{
	HIDE_TOPMENU : 'HIDE_TOPMENU',
	SHOW_TOPMENU : 'SHOW_TOPMENU',
	SHOW_MINIMENU : 'SHOW_MINIMENU',
	ADD_NEW_CHANNEL : 'ADD_NEW_CHANNEL',
	DELETE_CHANNEL : 'DELETE_CHANNEL',
	ADD_NEW_USER : 'ADD_NEW_USER',
	LOGIN : 'LOGIN'
}