export default{
	HIDE_TOPMENU : 'HIDE_TOPMENU',
	SHOW_TOPMENU : 'SHOW_TOPMENU',
	SHOW_MINIMENU : 'SHOW_MINIMENU',
	SWITCH_MENU: 'SWITCH_MENU',

	ADD_NEW_CHANNEL : 'ADD_NEW_CHANNEL',	
	DELETE_CHANNEL : 'DELETE_CHANNEL',

	ADD_NEW_USER : 'ADD_NEW_USER',
	ADD_NEW_USER_PAGE: 'ADD_NEW_USER_PAGE',

	ADD_NEW_CATEGORY_GROUP: 'ADD_NEW_CATEGORY_GROUP',
	ADD_NEW_CATEGORY : 'ADD_NEW_CATEGORY',	
	DELETE_CATEGORY: 'DELETE_CATEGORY',

	LOGIN : 'LOGIN',

	SWITCH_PAGE: 'SWITCH_PAGE',
	CATEGORY_PAGE: 'CATEGORY_PAGE',
	CHANNEL_PAGE: 'CHANNEL_PAGE',	
	USER_PAGE: 'USER_PAGE',
	MISC_PAGE: 'MISC_PAGE'
}